#!/bin/bash

# ─────────────────────────────────────────────────────────────────────────────
# Plane Fork - Deploy Manager (portable / works on any server)
# Builds YOUR fork's code into Docker images (from source) and runs them.
# Plane runs its OWN proxy (Caddy) on ports you choose - no external proxy needed.
# Safe updates: git pull -> rebuild -> up, WITHOUT touching data volumes.
#
# Repo : git@github.com:Zuneko-Labs/plane.git
# Uses : docker-compose.yml (root) -> build from source (NOT prebuilt images)
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ---- Static config ----------------------------------------------------------
REPO_URL="git@github.com:Zuneko-Labs/plane.git"
BRANCH="staging"
COMPOSE_FILE="docker-compose.yml"       # root file = build from source (your code)
PROJECT_NAME="plane"                    # docker compose project (volume prefix) - DO NOT change
CONF_FILE=".deploy.conf"                # stores non-secret answers
OVERRIDE_FILE="docker-compose.override.yml"   # optional, only if you add one manually
API_ENV="./apps/api/.env"
WEB_ENV="./apps/web/.env"
ROOT_ENV="./.env"

# ---- Colors -----------------------------------------------------------------
GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
BOLD='\033[1m'; NC='\033[0m'
msg()  { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}!${NC} $1"; }
err()  { echo -e "${RED}✗${NC} $1"; }
hdr()  { echo -e "\n${BOLD}${BLUE}$1${NC}"; }

# docker compose wrapper (pins file + project; includes override only if you made one)
dc() {
    local files=(-f "$COMPOSE_FILE")
    [ -f "$OVERRIDE_FILE" ] && files+=(-f "$OVERRIDE_FILE")
    docker compose -p "$PROJECT_NAME" "${files[@]}" "$@"
}

require_docker() {
    command -v docker >/dev/null 2>&1 || { err "docker not installed."; exit 1; }
    docker compose version >/dev/null 2>&1 || { err "docker compose plugin missing."; exit 1; }
}

# set_env KEY VALUE FILE -> replace existing KEY=... or append
set_env() {
    local key="$1" val="$2" file="$3"
    touch "$file"
    if grep -q "^${key}=" "$file"; then
        sed -i "s|^${key}=.*|${key}=${val}|" "$file"
    else
        echo "${key}=${val}" >> "$file"
    fi
}

load_conf() { [ -f "$CONF_FILE" ] && . "$CONF_FILE"; }
save_conf() {
    cat > "$CONF_FILE" <<EOF
# Generated by deploy.sh - non-secret answers (secrets live in .env files)
APP_URL="${APP_URL}"
HTTP_PORT="${HTTP_PORT}"
HTTPS_PORT="${HTTPS_PORT}"
TLS_MODE="${TLS_MODE}"
CERT_EMAIL="${CERT_EMAIL}"
SMTP_ENABLE="${SMTP_ENABLE}"
EOF
    msg "Saved config -> $CONF_FILE"
}

# ---- Port-in-use check ------------------------------------------------------
port_busy() {
    local p="$1"
    if command -v ss >/dev/null 2>&1; then ss -ltn 2>/dev/null | grep -q ":${p} "
    elif command -v netstat >/dev/null 2>&1; then netstat -ltn 2>/dev/null | grep -q ":${p} "
    else return 1; fi
}

# ---- Env file bootstrap -----------------------------------------------------
setup_env() {
    hdr "Setting up .env files"
    local services=("" "web" "api" "space" "admin" "live")
    for service in "${services[@]}"; do
        local prefix; [ -z "$service" ] && prefix="./" || prefix="./apps/$service/"
        local src="${prefix}.env.example" dst="${prefix}.env"
        [ -f "$src" ] || { warn "no example at $src (skip)"; continue; }
        if [ -f "$dst" ]; then warn "$dst exists (keep)"; else cp "$src" "$dst"; msg "created $dst"; fi
    done
    if [ -f "$API_ENV" ] && ! grep -q "^SECRET_KEY=" "$API_ENV"; then
        local key; key=$(tr -dc 'a-z0-9' < /dev/urandom | head -c50)
        echo "SECRET_KEY=\"$key\"" >> "$API_ENV"; msg "generated SECRET_KEY"
    fi
}

# ---- Interactive: URL + ports + TLS + SMTP ---------------------------------
prompt_config() {
    load_conf
    hdr "Deployment configuration"
    echo "Access URL = how users reach Plane (scheme + host + optional :port)."
    echo "  Test/IP example : http://76.13.240.193:8090"
    echo "  Domain example  : https://plane.zuneko.in"
    read -rp "Access URL [${APP_URL:-}]: " _u
    APP_URL="${_u:-${APP_URL:-}}"
    while [ -z "$APP_URL" ]; do read -rp "Access URL required: " APP_URL; done

    echo
    echo "TLS / HTTPS handling:"
    echo "  1) none  - serve plain HTTP (testing, custom port, or behind another proxy)"
    echo "  2) auto  - Plane's Caddy gets a free Let's Encrypt cert"
    echo "             (needs a real DOMAIN in the URL + host ports 80 AND 443 free + DNS set)"
    read -rp "Choose [${TLS_MODE:-1}]: " _t
    case "${_t:-${TLS_MODE:-1}}" in 2) TLS_MODE="auto" ;; *) TLS_MODE="none" ;; esac

    if [ "$TLS_MODE" = "auto" ]; then
        HTTP_PORT="${HTTP_PORT:-80}"; HTTPS_PORT="${HTTPS_PORT:-443}"
        read -rp "HTTP host port  [${HTTP_PORT}]: "  _h; HTTP_PORT="${_h:-$HTTP_PORT}"
        read -rp "HTTPS host port [${HTTPS_PORT}]: " _s; HTTPS_PORT="${_s:-$HTTPS_PORT}"
        read -rp "Email for Let's Encrypt [${CERT_EMAIL:-}]: " _e; CERT_EMAIL="${_e:-${CERT_EMAIL:-}}"
    else
        HTTP_PORT="${HTTP_PORT:-8090}"; HTTPS_PORT="${HTTPS_PORT:-8453}"
        read -rp "HTTP host port  [${HTTP_PORT}]: "  _h; HTTP_PORT="${_h:-$HTTP_PORT}"
        read -rp "HTTPS host port (spare, keep free) [${HTTPS_PORT}]: " _s; HTTPS_PORT="${_s:-$HTTPS_PORT}"
        CERT_EMAIL="${CERT_EMAIL:-}"
    fi

    for p in "$HTTP_PORT" "$HTTPS_PORT"; do
        if port_busy "$p"; then warn "port $p is ALREADY in use on this host - pick a free one or it will fail."; fi
    done

    echo
    read -rp "Configure SMTP now? (y/N) [${SMTP_ENABLE:-N}]: " _se
    if [[ "${_se:-}" =~ ^[Yy] ]]; then
        SMTP_ENABLE="Y"
        read -rp "  SMTP host (e.g. smtp.gmail.com): " SMTP_HOST
        read -rp "  SMTP port [587]: " SMTP_PORT; SMTP_PORT="${SMTP_PORT:-587}"
        read -rp "  SMTP username (email): " SMTP_USER
        read -rsp "  SMTP app password: " SMTP_PASS; echo
        read -rp "  From address [${SMTP_USER:-}]: " SMTP_FROM; SMTP_FROM="${SMTP_FROM:-$SMTP_USER}"
        read -rp "  Use TLS? (1/0) [1]: " SMTP_TLS; SMTP_TLS="${SMTP_TLS:-1}"
        read -rp "  Use SSL? (1/0) [0]: " SMTP_SSL; SMTP_SSL="${SMTP_SSL:-0}"
    else
        SMTP_ENABLE="${SMTP_ENABLE:-N}"
    fi
    save_conf
}

# ---- Write env from config --------------------------------------------------
apply_config() {
    load_conf
    [ -n "${APP_URL:-}" ] || { err "No config yet. Run configure first."; return 1; }
    hdr "Applying config for ${APP_URL}"

    # Backend URLs + CORS
    set_env "WEB_URL"              "${APP_URL}" "$API_ENV"
    set_env "CORS_ALLOWED_ORIGINS" "${APP_URL}" "$API_ENV"
    set_env "APP_BASE_URL"         "${APP_URL}" "$API_ENV"
    set_env "ADMIN_BASE_URL"       "${APP_URL}" "$API_ENV"
    set_env "SPACE_BASE_URL"       "${APP_URL}" "$API_ENV"
    set_env "LIVE_BASE_URL"        "${APP_URL}" "$API_ENV"
    set_env "DEBUG"                "0"          "$API_ENV"

    # Frontend URLs (single origin; proxy handles sub-paths)
    set_env "VITE_API_BASE_URL"   ""           "$WEB_ENV"
    set_env "VITE_WEB_BASE_URL"   "${APP_URL}" "$WEB_ENV"
    set_env "VITE_ADMIN_BASE_URL" "${APP_URL}" "$WEB_ENV"
    set_env "VITE_SPACE_BASE_URL" "${APP_URL}" "$WEB_ENV"
    set_env "VITE_LIVE_BASE_URL"  "${APP_URL}" "$WEB_ENV"

    # MinIO endpoint (dockerized) + enable, so uploads work inside compose network
    set_env "AWS_S3_ENDPOINT_URL" "http://plane-minio:9000" "$API_ENV"
    set_env "USE_MINIO"           "1"                        "$API_ENV"
    # Live server secret must match between api and the live service
    set_env "LIVE_SERVER_SECRET_KEY" "secret-key" "$API_ENV"
    set_env "LIVE_SERVER_SECRET_KEY" "secret-key" "$ROOT_ENV"
    set_env "API_BASE_URL"           "http://api:8000" "$ROOT_ENV"

    # SMTP -> API env (seeded into DB on first boot; smtp-sync to change later)
    if [ "${SMTP_ENABLE:-N}" = "Y" ] && [ -n "${SMTP_HOST:-}" ]; then
        set_env "ENABLE_SMTP"         "1"            "$API_ENV"
        set_env "EMAIL_HOST"          "${SMTP_HOST}" "$API_ENV"
        set_env "EMAIL_PORT"          "${SMTP_PORT}" "$API_ENV"
        set_env "EMAIL_HOST_USER"     "${SMTP_USER}" "$API_ENV"
        set_env "EMAIL_HOST_PASSWORD" "${SMTP_PASS}" "$API_ENV"
        set_env "EMAIL_FROM"          "${SMTP_FROM}" "$API_ENV"
        set_env "EMAIL_USE_TLS"       "${SMTP_TLS}"  "$API_ENV"
        set_env "EMAIL_USE_SSL"       "${SMTP_SSL}"  "$API_ENV"
        msg "SMTP written to apps/api/.env"
    fi

    # Proxy host ports
    set_env "LISTEN_HTTP_PORT"  "${HTTP_PORT}"  "$ROOT_ENV"
    set_env "LISTEN_HTTPS_PORT" "${HTTPS_PORT}" "$ROOT_ENV"

    # Caddy SITE_ADDRESS: domain => auto-HTTPS, else plain :80
    if [ "${TLS_MODE}" = "auto" ]; then
        local host="${APP_URL#*://}"; host="${host%%/*}"; host="${host%%:*}"
        set_env "SITE_ADDRESS" "${host}"        "$ROOT_ENV"
        set_env "CERT_EMAIL"   "${CERT_EMAIL}"  "$ROOT_ENV"
        msg "Caddy auto-HTTPS for ${host} (needs 80+443 + DNS)"
    else
        set_env "SITE_ADDRESS" ":80"            "$ROOT_ENV"
        msg "Plain HTTP on host port ${HTTP_PORT} -> ${APP_URL}"
    fi
    msg "Config applied."
}

# ---- Deploy flows -----------------------------------------------------------
first_deploy() {
    require_docker
    setup_env
    [ -f "$CONF_FILE" ] || prompt_config
    apply_config
    hdr "Building images from YOUR source (first build slow: 10-20 min)"
    dc build
    hdr "Starting all services"
    dc up -d
    msg "Deployed. Open: ${APP_URL}  (status: option 7, logs: option 8)"
}

update_deploy() {
    require_docker
    hdr "Pulling latest from $BRANCH"
    git fetch origin "$BRANCH"; git checkout "$BRANCH"; git pull origin "$BRANCH"
    apply_config || true
    hdr "Rebuilding images (changed layers only)"; dc build
    hdr "Recreating containers (volumes preserved)"; dc up -d   # NO -v => data safe
    dc image prune -f >/dev/null 2>&1 || true
    msg "Updated. Data volumes untouched."
}

reconfigure() {
    require_docker
    prompt_config; apply_config
    read -rp "Apply now (rebuild web+api + restart)? (Y/n): " a
    if [[ ! "${a:-Y}" =~ ^[Nn] ]]; then
        dc build web api; dc up -d
        [ "${SMTP_ENABLE:-N}" = "Y" ] && smtp_resync
        msg "Reconfigured + restarted."
    fi
}

# SMTP change-later: configure_instance only SEEDS (get_or_create). Force reseed.
smtp_resync() {
    require_docker
    hdr "Re-syncing SMTP from env into DB"
    dc exec -T api python manage.py shell -c \
        "from plane.license.models import InstanceConfiguration as C; print('cleared', C.objects.filter(category='SMTP').delete())"
    dc exec -T api python manage.py configure_instance
    dc restart api worker beat-worker
    msg "SMTP re-synced. (Or edit live in god-mode: ${APP_URL:-<url>}/god-mode)"
}

test_email() {
    require_docker
    read -rp "Send test email to: " to
    [ -z "$to" ] && { err "no address"; return; }
    dc exec -T api python manage.py test_email "$to" || warn "test_email failed - check SMTP + logs"
}

rebuild_one() {
    require_docker
    read -rp "Service (web/admin/space/api/worker/beat-worker/live/proxy): " svc
    [ -z "$svc" ] && { err "no service"; return; }
    dc build "$svc"; dc up -d "$svc"; msg "$svc rebuilt + restarted."
}

stop_all()    { require_docker; dc stop;    msg "Stopped (data kept)."; }
start_all()   { require_docker; dc up -d;   msg "Started."; }
restart_all() { require_docker; dc restart; msg "Restarted."; }
status()      { require_docker; dc ps; }
logs()        { require_docker; dc logs -f --tail=100; }

inspect_host() {
    require_docker
    hdr "Published host ports in use (pick free ones for Plane)"
    docker ps --format '{{.Names}}\t{{.Ports}}' | grep -E '0.0.0.0|:::' || echo "none"
    hdr "Listening TCP ports"
    (ss -ltn 2>/dev/null || netstat -ltn 2>/dev/null) | tail -n +1 || warn "ss/netstat not found"
}

backup_db() {
    require_docker
    local out="./backup-plane-db-$(date +%Y%m%d-%H%M%S).sql"
    hdr "Dumping Postgres -> $out"
    dc exec -T plane-db sh -c 'pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB"' > "$out"
    msg "Backup saved: $out"
}

destroy_all() {
    require_docker
    warn "This DELETES ALL DATA (db, uploads, redis, rabbitmq)."
    read -rp "Type 'DELETE' to confirm: " c
    if [ "$c" = "DELETE" ]; then dc down -v; err "All containers + volumes removed."; else msg "Cancelled."; fi
}

# ---- Menu -------------------------------------------------------------------
menu() {
    echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}${BLUE}        Plane Fork - Deploy Manager${NC}"
    echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo "  1) First-time deploy       (env + config + build + up)"
    echo "  2) Update & redeploy       (git pull + rebuild + up, NO data loss)"
    echo "  3) Configure URL/ports/SMTP"
    echo "  4) Re-sync SMTP from env    5) Send test email"
    echo "  6) Rebuild one service"
    echo "  7) Status                   8) Logs"
    echo "  9) Start   10) Stop (keep data)   11) Restart"
    echo "  12) Backup database         i) Inspect host ports"
    echo -e "  ${RED}D) DESTROY everything (delete data)${NC}"
    echo "  0) Exit"
    echo -en "${BOLD}Choose: ${NC}"
}

# ---- Non-interactive entry --------------------------------------------------
if [ "${1:-}" != "" ]; then
    case "$1" in
        first)      first_deploy ;;
        update)     update_deploy ;;
        configure)  reconfigure ;;
        smtp-sync)  smtp_resync ;;
        test-email) test_email ;;
        stop)       stop_all ;;
        start)      start_all ;;
        restart)    restart_all ;;
        status)     status ;;
        logs)       logs ;;
        backup)     backup_db ;;
        inspect)    inspect_host ;;
        *) err "Unknown: $1"; echo "  first|update|configure|smtp-sync|test-email|stop|start|restart|status|logs|backup|inspect"; exit 1 ;;
    esac
    exit 0
fi

while true; do
    menu; read -r choice
    case "$choice" in
        1) first_deploy ;;
        2) update_deploy ;;
        3) reconfigure ;;
        4) smtp_resync ;;
        5) test_email ;;
        6) rebuild_one ;;
        7) status ;;
        8) logs ;;
        9) start_all ;;
        10) stop_all ;;
        11) restart_all ;;
        12) backup_db ;;
        i|I) inspect_host ;;
        D|d) destroy_all ;;
        0) exit 0 ;;
        *) err "Invalid choice" ;;
    esac
done
