# Generated by Django 4.2.30 on 2026-08-17 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_issuerecurrence_occurrences'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sequence', models.BigIntegerField(editable=False, null=True)),
                ('dispatch_seq', models.BigIntegerField(editable=False, null=True, unique=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('schema_version', models.SmallIntegerField(default=1)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'db_table': 'event_log',
                'ordering': ('sequence',),
                'indexes': [models.Index(fields=['workspace', 'dispatch_seq'], name='event_log_ws_dispatch_idx'), models.Index(fields=['occurred_at'], name='event_log_occurred_idx'), models.Index(condition=models.Q(('dispatched_at__isnull', True)), fields=['dispatched_at'], name='event_log_pending_idx')],
            },
        ),
        # `sequence` cannot be a GENERATED ALWAYS AS IDENTITY column: Django's
        # ORM always sends an explicit value (including NULL) for every field
        # on INSERT, and identity columns only auto-generate when the column
        # is omitted from the insert list entirely — an explicit NULL is a
        # value, not an omission, and either violates NOT NULL or (for
        # GENERATED BY DEFAULT) is accepted as NULL rather than replaced.
        # A BEFORE INSERT trigger sidesteps this: it fires on every row
        # regardless of how the NULL arrived, fills in the next sequence
        # value, and only then does Postgres check the NOT NULL/UNIQUE
        # constraints below — giving the same "auto-increment, insert order,
        # never assigned twice" guarantee as an identity column.
        migrations.RunSQL(
            sql="""
                CREATE SEQUENCE event_log_sequence_seq;

                CREATE OR REPLACE FUNCTION event_log_assign_sequence()
                RETURNS trigger AS $$
                BEGIN
                    IF NEW.sequence IS NULL THEN
                        NEW.sequence := nextval('event_log_sequence_seq');
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER event_log_assign_sequence_trg
                BEFORE INSERT ON event_log
                FOR EACH ROW EXECUTE FUNCTION event_log_assign_sequence();

                ALTER SEQUENCE event_log_sequence_seq OWNED BY event_log.sequence;
                ALTER TABLE event_log ALTER COLUMN sequence SET NOT NULL;
                ALTER TABLE event_log ADD CONSTRAINT event_log_sequence_key UNIQUE (sequence);

                -- Not attached to the dispatch_seq column the same way: it is
                -- stamped by the relay (Phase 3), post-commit, one row at a
                -- time under an advisory lock, not by a per-row trigger.
                CREATE SEQUENCE event_log_dispatch_seq_seq;
            """,
            reverse_sql="""
                DROP SEQUENCE IF EXISTS event_log_dispatch_seq_seq;
                ALTER TABLE event_log DROP CONSTRAINT IF EXISTS event_log_sequence_key;
                ALTER TABLE event_log ALTER COLUMN sequence DROP NOT NULL;
                DROP TRIGGER IF EXISTS event_log_assign_sequence_trg ON event_log;
                DROP FUNCTION IF EXISTS event_log_assign_sequence();
                DROP SEQUENCE IF EXISTS event_log_sequence_seq;
            """,
        ),
    ]
