# Generated by Django 4.2.30 on 2026-08-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='outbox_event_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
